Fixed issue with "apply" and "syllabus" buttons
4GeeksAcademy/website-v2 pull request #1111
Opened 2021-09-27 13:57 UTC by LuxSalgado

Modified the course.js to correctly display the "apply" and "syllabus" buttons following the website page context language.

Other isuues:

- In the header of the https://4geeksacademy.com/us/coding-bootcamps/full-time-full-stack-developer/ page when the website is in English it shows the word "Cooding" and it should show "Coding". I don't know if it only happens in Caracas or in other places as well.
- In one of the Navbar buttons, when the website is in Spanish, it shows "PORQUÉ 4GEEKS" and it should be "POR QUÉ 4GEEKS"

2021-09-27 15:21 UTC, alesanchezr commented
#### 📝 Changed routes:


| [**/404**](https://website-v2-abylggrsd-geeksacademy.vercel.app/404) |
|:-:|
|<a href="https://website-v2-abylggrsd-geeksacademy.vercel.app/404"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/xD1BZIv36YU6XfSfBwHxtJqY7wIcGmxNeilW802cNXRmkate0mnj1oWxlD2eB-CAmflCGTuP7rIBGTXJrapZXw.png&w=600" alt="Screenshot of /404" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/lWKFVVj4cHqPYQzECtK-9dl84ud-c-pwgr_lKIuo4b7Q_95N0lMiCNkbXXILv5im02-P-qgH4lBk-VSZpG5JGQ.png">(view full size)</a> |







Commit b522eb64ec8663e387c96b8ee5b14825c866481d (https://website-v2-abylggrsd-geeksacademy.vercel.app).

2021-09-27 15:23 UTC, ArielCalisaya requested changes

2021-09-27 15:23 UTC, ArielCalisaya commented on src/templates/course.js
> +  const apply_button_text = session && session.location ? applyButtonText : "Apply";
This is an unnecessary lines of code, you should use the `applyButtonText` state instead of the ~~`apply_button_text`~~ variable

2021-09-28 19:25 UTC, ArielCalisaya approved these changes

2021-10-02 13:57 UTC, alesanchezr approved these changes

2021-10-02 13:57 UTC, merged