Update santiago-chile.es.yaml
4GeeksAcademy/website-v2 pull request #1283
Opened 2022-04-04 21:33 UTC by gabrielavera

Custom bar update from march promotion to: ¿QUISIERAS TU PRIMER TRABAJO COMO PROGRAMADOR? ¡CONVIÉRTE EN FULL STACK DEVELOPER Y CONSÍGUELO!

2022-04-05 02:03 UTC, alesanchezr approved these changes

2022-04-05 02:03 UTC, alesanchezr requested changes
Te hace falta la traduccion en ingles tambien.

2022-04-06 19:19 UTC, gabrielavera commented
Lista la traducción al ingles

2022-04-20 14:28 UTC, jatv93 requested changes
No puede ir todo en mayúscula

2022-04-20 14:43 UTC, merged