Refrescamiento award page
4GeeksAcademy/website-v2 pull request #1829
Opened 2023-10-31 21:12 UTC by kelvinruizdevel

/es/premios

2023-11-14 21:37 UTC, tommygonzaleza approved these changes

2023-11-14 21:38 UTC, tommygonzaleza commented
Solucionar conflictos

2023-11-14 22:37 UTC, tommygonzaleza requested changes

2023-11-14 22:37 UTC, tommygonzaleza commented on src/data/blog/delete-me.md
> +loren ipsun.
Error al solucionar el conflicto

2023-11-21 22:36 UTC, alesanchezr approved these changes

2023-11-21 22:36 UTC, merged