Issue 6209
4GeeksAcademy/website-v2 pull request #1944
Opened 2024-02-07 02:18 UTC by Khrisefzm

Add pading and width in diferent sections
Add correct link in the button

2024-02-07 02:18 UTC, Khrisefzm commented
Issue link:
https://github.com/orgs/breatheco-de/projects/8/views/1?filterQuery=assignee%3A%40me&pane=issue&itemId=49859365

2024-02-20 18:38 UTC, tommygonzaleza requested changes

2024-02-20 18:38 UTC, tommygonzaleza commented on src/data/page/job-guarantee.es.yml
> +      path: "/es/aplica"
Dejalo con `#top`

2024-02-20 18:38 UTC, tommygonzaleza commented on src/data/page/job-guarantee.us.yml
> +      path: "/us/apply"
Dejalo con `#top`

2024-02-20 18:38 UTC, tommygonzaleza commented on src/templates/job-guarantee.js
> +        maxWidth="1695px"
El max-width de nuestra pagina es 1366px

2024-02-23 03:35 UTC, Khrisefzm commented on src/components/Sections/index.js
Añadí las mismas propiedades que el Div, porque nunca se ha usado el elemento Container en algún file. Los únicos elementos que tienen unan Container del Section son Wrapper y WrapperImage creados en el mismo seccion, pero nunca son usados en ningún otro file.

2024-02-27 18:29 UTC, tommygonzaleza approved these changes

2024-02-27 21:41 UTC, tommygonzaleza approved these changes

2024-03-21 14:35 UTC, alesanchezr approved these changes

2024-03-21 14:35 UTC, merged