aling items
4GeeksAcademy/website-v2 pull request #1951
Opened 2024-02-09 04:41 UTC by Khrisefzm

2024-02-09 04:41 UTC, Khrisefzm commented
Issue Link: https://github.com/orgs/breatheco-de/projects/8/views/1?filterQuery=assignee%3A%40me&pane=issue&itemId=52556616

2024-02-20 18:23 UTC, tommygonzaleza requested changes

2024-02-20 18:23 UTC, tommygonzaleza commented on src/components/Sections/index.js
> +              paddingTitle ? paddingTitle : paddingTitle_tablet || "0 20px"
No debe ser mas prioritario el paddingTitle_tablet que el paddingTitle en este caso?

2024-02-20 18:23 UTC, tommygonzaleza commented on src/components/Sections/index.js
> +              paddingParagraph ? paddingParagraph : paddingParagraph_tablet || 0
No debe ser mas prioritario el paddingTitle_tablet que el paddingTitle en este caso?

2024-02-20 18:23 UTC, tommygonzaleza commented on src/templates/landing_post.js
> +          padding_tablet="90px 8% 70px 4%"
No lo resuelvas con porcentajes y agregandoles unos paddings desde aca. El componente header debe tener un max-width del que no debe pasarse ademas, este debe tener un padding por defecto, asi como funciona bootstrap con la clase container que le aplica cierto padding

2024-03-05 21:31 UTC, tommygonzaleza approved these changes

2024-03-12 19:45 UTC, merged