Issue 6847
4GeeksAcademy/website-v2 pull request #1960
Opened 2024-02-16 01:26 UTC by Khrisefzm

Create checkboxes for privacy politics and whatsapp

2024-02-20 18:20 UTC, tommygonzaleza requested changes

2024-02-20 18:20 UTC, tommygonzaleza commented on src/components/LeadForm/index.js
> +                        {consent.url ? (
En vez de tener un valor `consent.url` y que siempre este fijo al final. Debemos agregarlos desde el YML con HTML. Actualmente si recibimos un HTML en el valor de un campo del YML, se transforma. Entonces simplemente debe agregarse como un anchor con la etiqueta HTML

2024-02-20 18:20 UTC, tommygonzaleza commented on src/data/page/privacy-policy.es.yml
> +wa_consent:
Ya no hace falta, debes quitarlo

2024-02-20 18:20 UTC, tommygonzaleza commented on src/templates/apply.js
> +                          <a
En vez de tener un valor `consent.url` y que siempre este fijo al final. Debemos agregarlos desde el YML con HTML. Actualmente si recibimos un HTML en el valor de un campo del YML, se transforma. Entonces simplemente debe agregarse como un anchor con la etiqueta HTML

2024-02-27 18:40 UTC, tommygonzaleza requested changes

2024-02-27 18:40 UTC, tommygonzaleza commented on src/data/location/costa-rica.es.yaml
> +    message: 'Al completar este formulario acepto que mi información será utilizada para enviarme información comercial sobre 4Geeks Academy y que podria resultar una relación comercial a partir de e
Podría debe tener acento, cambialo en todos los YMLs de español

2024-02-27 21:39 UTC, tommygonzaleza approved these changes

2024-02-29 14:18 UTC, alesanchezr approved these changes

2024-02-29 14:18 UTC, merged