Update index.es.yml
4GeeksAcademy/website-v2 pull request #323
Opened 2020-09-29 15:05 UTC by victormgomezp

algunos cambios en español y corrección de errores ortográficos

2020-09-29 16:19 UTC, Riciglianomarcelo commented on src/data/page/index.es.yml
> +  sub_heading: Uniéndote a 4Geeks obtendrás acceso a mentorías de por vida y apoyo de carrera ilimitado.
Programa tu historia se debe quedar porque es un mensaje muy potente en todas las sedes. Vamos a dejarlo y a incorporar lo que comentan justo debajo.

2020-09-29 16:27 UTC, Riciglianomarcelo requested changes
Revisar los comentarios que coloqué.

2020-09-29 16:42 UTC, victormgomezp commented on src/data/page/index.es.yml
> +  sub_heading: Uniéndote a 4Geeks obtendrás acceso a mentorías de por vida y apoyo de carrera ilimitado.
Vale, en españa programa tu historia no significa nada, no usamos esa frase, pero entiendo que en el resto de países de latam si.  Me parece bien que quede abajo.

2020-09-29 20:53 UTC, victormgomezp commented on src/data/page/index.es.yml
> +  sub_heading: Uniéndote a 4Geeks obtendrás acceso a mentorías de por vida y apoyo de carrera ilimitado.
Debajo del sub_heading no hay espacio, yo entiendo que la frase programa tu historia sea fuerte pero creo que en este caso, donde no hay más espacio, es más fuerte las ventajas que tendrás al unirte a 4Geeks que solo "Programa tu historia" de hecho en la versión en inglés tienen un texto similar

2020-09-30 19:53 UTC, alesanchezr commented
Estoy rechazando el PR pero en realidad aplique todos los cambios menos el de `Programa tu historia` que lo cambiamos a otra cosa.

2020-09-30 19:53 UTC, closed without merging