Update madrid-spain.es.yaml
4GeeksAcademy/website-v2 pull request #546
Opened 2021-03-12 14:04 UTC by marcelovaldebenito

2021-03-13 00:28 UTC, alesanchezr reviewed
Asi tan pequeña? Las mejores practicas de SEO no dicen que esta descripcion debe ser mas larga?

2021-03-13 00:29 UTC, alesanchezr requested changes

2021-03-13 00:29 UTC, alesanchezr commented on src/data/location/madrid-spain.es.yaml
> +  description: "Coding bootcamp en Madrid, España"
asi tan pequeña? esto cumple con las mejores practicas de SEO?

2021-03-15 16:12 UTC, marcelovaldebenito commented on src/data/location/madrid-spain.es.yaml
> +  description: "Coding bootcamp en Madrid, España"
No tiene mínimo, pero el máximo recomendado es de 160 caracteres, voy a agregarle la info sobre cada campus que aparece en el sitio para que quede más atractivo

2021-04-21 19:09 UTC, merged